test:
	guile -s unification.scm
	guile -s records.scm
	guile -s language.scm
	guile -s lists.scm
	guile -s peano.scm
	guile -s goat.scm
	guile -s dcg.scm

colors:
	guile -s four-color.scm

expunif:
	guile -s exponential-unification.scm
