(use-modules (minikanren language)
	     (minikanren examples peano))
(use-modules (srfi srfi-64))

(test-begin "peano fair")
(test-equal (run^ 10 (lambda (q)
		       (fresh (x y)
			 (== q (list x y))
			 (peano x)
			 (peano y))))
  '(((z z) where)
    ((z (s z)) where)
    (((s z) z) where)
    ((z (s (s z))) where)
    ((z (s (s (s z)))) where)
    (((s z) (s z)) where)
    ((z (s (s (s (s z))))) where)
    ((z (s (s (s (s (s z)))))) where)
    (((s (s z)) z) where)
    (((s z) (s (s z))) where)))
(test-end "peano fair")

(test-begin "peano dfs")
(test-equal (run^ 3 (lambda (q)
		      (fresh/dfs (x y)
				 (== q (list x y))
				 (peano/dfs x)
				 (peano/dfs y))))
  '(((z z) where)
    ((z (s z)) where)
    ((z (s (s z))) where)))
(test-end "peano dfs")
